fit:
  seed_everything: 27
  trainer:
    logger:
      - class_path: pytorch_lightning.loggers.WandbLogger
        init_args:
          name: arcface_tf_efficientnet_b0_crops_cyclelr_3e-4
          project: HappyWhale
          log_model: True
    callbacks:
      - class_path: pytorch_lightning.callbacks.EarlyStopping
        init_args:
          monitor: val_loss
          patience: 30
          min_delta: 0.001
          verbose: true
      - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    checkpoint_callback: null
    enable_checkpointing: true
    default_root_dir: 'logs'
    gradient_clip_val: null
    gradient_clip_algorithm: null
    process_position: 0
    num_nodes: 1
    num_processes: 10
    devices: null
    gpus: [1]
    auto_select_gpus: false
    tpu_cores: null
    ipus: null
    log_gpu_memory: null
    progress_bar_refresh_rate: null
    enable_progress_bar: true
    overfit_batches: 0.0
    track_grad_norm: -1
    check_val_every_n_epoch: 1
    fast_dev_run: false
    accumulate_grad_batches: null
    max_epochs: 15
    min_epochs: null
    max_steps: -1
    min_steps: null
    max_time: null
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    limit_test_batches: 1.0
    limit_predict_batches: 1.0
    val_check_interval: 1.0
    flush_logs_every_n_steps: null
    log_every_n_steps: 50
    accelerator: null
    strategy: null
    sync_batchnorm: false
    precision: 32
    enable_model_summary: true
    weights_summary: top
    weights_save_path: null
    num_sanity_val_steps: 2
    resume_from_checkpoint: null
    profiler: null
    benchmark: false
    deterministic: false
    reload_dataloaders_every_n_epochs: 0
    reload_dataloaders_every_epoch: false
    auto_lr_find: false
    replace_sampler_ddp: true
    detect_anomaly: false
    auto_scale_batch_size: false
    prepare_data_per_node: null
    plugins: null
    amp_backend: native
    amp_level: null
    move_metrics_to_cpu: false
    multiple_trainloader_mode: max_size_cycle
    stochastic_weight_avg: false
    terminate_on_nan: null
  ckpt_path: null
  model:
    class_path: modules.training.train.ClassificationLightningModel
    init_args:
      dataset_folder: /home/vadim-tsitko/Data/whl/train_images
      dataframe_path: /home/vadim-tsitko/Data/whl/crops/train.csv
      model_type: tf_efficientnet_b0
      shuffle: true
      size:
      - 512
      - 512
      batch_size: 32
      num_processes: 28
      learning_rate: 3e-4
      classes: 15587
      num_folds: 5
      dataset_part: 1.0
      use_boxes: true
      label_smoothing: 0.1
      in_channels: 1
